# Build All
all: crawler-all app-all

# Cleans all
clean: crawler-clean app-clean

# Specific Rules
crawler-all:
	$(MAKE) -C crawler all

app-all:
	$(MAKE) -C app all

crawler-clean:
	$(MAKE) -C crawler clean

app-clean:
	$(MAKE) -C app clean
